# Generated by Django 5.2.9 on 2025-12-29 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_empresamodel_id_alter_rolmodel_id_and_more'),
        ('usuarios', '0002_usuariomodel_arl_usuariomodel_eps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariomodel',
            name='rol',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='management.rolmodel'),
            preserve_default=False,
        ),
    ]
