# Generated by Django 5.2.9 on 2025-12-29 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0003_alter_empresamodel_id_alter_rolmodel_id_and_more'),
        ('usuarios', '0003_usuariomodel_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada', models.DateTimeField()),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('EPP_entregados', models.BooleanField(default=False)),
                ('Informacion_recibida', models.BooleanField(default=True)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.sedemodel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariomodel')),
            ],
            options={
                'indexes': [models.Index(fields=['usuario', 'fecha'], name='attendance__usuario_bdc90c_idx'), models.Index(fields=['hora_salida'], name='attendance__hora_sa_d11542_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('hora_salida__isnull', True)), fields=('usuario', 'fecha'), name='una_entrada_abierta_por_usuario_por_dia')],
            },
        ),
    ]
