# Generated by Django 5.2.9 on 2025-12-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroentrada',
            name='placa_vehiculo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
