# Generated by Django 5.2.9 on 2026-01-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_registroentrada_placa_vehiculo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registroentrada',
            name='una_entrada_abierta_por_usuario_por_dia',
        ),
        migrations.AddField(
            model_name='registroentrada',
            name='documento_conductor_externo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registroentrada',
            name='es_caragueDescargue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registroentrada',
            name='nombre_conductor_externo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registroentrada',
            name='peso_final',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='registroentrada',
            name='peso_inicial',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
