# Generated by Django 5.2.9 on 2026-01-15 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_registroentrada_una_entrada_abierta_por_usuario_por_dia_and_more'),
        ('management', '0003_alter_empresamodel_id_alter_rolmodel_id_and_more'),
        ('usuarios', '0003_usuariomodel_rol'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroentrada',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehiculos.vehiculomodel'),
        ),
        migrations.AlterField(
            model_name='registroentrada',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariomodel'),
        ),
        migrations.AddIndex(
            model_name='registroentrada',
            index=models.Index(fields=['vehiculo', 'fecha'], name='attendance__vehicul_beff26_idx'),
        ),
        migrations.AddConstraint(
            model_name='registroentrada',
            constraint=models.UniqueConstraint(condition=models.Q(('hora_salida__isnull', True), ('usuario__isnull', True)), fields=('usuario', 'fecha'), name='una_entrada_abierta_por_usuario_por_dia'),
        ),
        migrations.AddConstraint(
            model_name='registroentrada',
            constraint=models.UniqueConstraint(condition=models.Q(('hora_salida__isnull', True), ('vehiculo__isnull', True)), fields=('vehiculo', 'fecha'), name='un_vehiculo_entrada_abierta_por_dia'),
        ),
    ]
