# Generated by Django 5.2.9 on 2026-01-15 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0003_alter_empresamodel_id_alter_rolmodel_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=15, unique=True)),
                ('tipo_vehiculo', models.CharField(choices=[('PESADO', 'Carga / Pesado'), ('LIVIANO', 'Particular / Liviano'), ('MOTOCICLETA', 'Motocicleta')], default='LIVIANO', max_length=30)),
                ('soat_vigente', models.BooleanField()),
                ('tecnomecanica_vigente', models.BooleanField()),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.empresamodel')),
            ],
        ),
    ]
