# Generated by Django 5.2.9 on 2025-12-29 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=255)),
                ('Tipo_empresa', models.CharField(choices=[('Interna', 'Interna'), ('Externa', 'Externa')], max_length=10)),
                ('nit', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RolModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rol', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SedeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sede', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=255)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.empresamodel')),
            ],
        ),
    ]
